// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"official/PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"ButtonPicture","status":false,"description":"Makes a picture clickable.","parameters":{}},
{"name":"AltSaveScreen","status":false,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"official/EventCommandByCode","status":false,"description":"Plugin for Event Command Execution via Code Specification","parameters":{}},
{"name":"official/ExtraImage","status":false,"description":"Extra Image Display Per Scene Plugin","parameters":{"ImageList":"[\"{\\\"SceneName\\\":\\\"Scene_Title\\\",\\\"FileName\\\":\\\"SF_People1_2\\\",\\\"X\\\":\\\"0\\\",\\\"Y\\\":\\\"0\\\",\\\"ScaleX\\\":\\\"100\\\",\\\"ScaleY\\\":\\\"100\\\",\\\"Opacity\\\":\\\"255\\\",\\\"BlendMode\\\":\\\"0\\\",\\\"Origin\\\":\\\"0\\\",\\\"Priority\\\":\\\"0\\\",\\\"Switch\\\":\\\"0\\\"}\"]"}},
{"name":"official/ExtraWindow","status":false,"description":"Extra Window Display Per Scene Plugin","parameters":{"WindowList":"[\"{\\\"SceneName\\\":\\\"Scene_Title\\\",\\\"x\\\":\\\"300\\\",\\\"y\\\":\\\"300\\\",\\\"width\\\":\\\"200\\\",\\\"height\\\":\\\"0\\\",\\\"LineHeight\\\":\\\"36\\\",\\\"Text\\\":\\\"hello extra window\\\",\\\"FontSize\\\":\\\"20\\\",\\\"WindowSkin\\\":\\\"Window\\\",\\\"SwitchId\\\":\\\"0\\\",\\\"ShowOpenAnimation\\\":\\\"true\\\"}\"]"}},
{"name":"official/MaterialBase","status":false,"description":"Material Base Plugin","parameters":{"ImageList":"[\"{\\\"Id\\\":\\\"img\\\",\\\"FilePath\\\":\\\"titles2/Floral\\\"}\"]","AudioList":"[]"}},
{"name":"official/RegionBase","status":false,"description":"Region Base Plugin","parameters":{"regionList":"[]","terrainTagList":"[]"}},
{"name":"official/TextScriptBase","status":false,"description":"Text Script Base Plugin","parameters":{"TextList":"[]"}},
{"name":"official/UniqueDataLoader","status":false,"description":"Unique Data Loading Plugin","parameters":{"GlobalVariableName":"$dataUniques","UniqueDataList":"[]"}},
{"name":"launch/Yami_8DirEx","status":true,"description":"Player can 8-dir move, also touch input movement.","parameters":{"dir4 Switch ID":"100"}},
{"name":"launch/WeatherOnBattle","status":false,"description":"[Ver1.1.0]display weather not only map but also battle","parameters":{}},
{"name":"launch/DevToolsManage","status":false,"description":"Development Support Plugin","parameters":{"StartupDevTool":"true","ShortcutList":"","ShowFPS":"OFF","CutTitle":"false","RapidStart":"false","RapidSpeed":"2","SlowSpeed":"2","InvalidMessageSkip":"false","MenuBarVisible":"true","ClickMenu":"1","OutputStartupInfo":"true","StartupOnTop":"false","UseReloadData":"true"}},
{"name":"launch/EventEffects","status":false,"description":"[Ver 1.1.3] set various effects to events and player","parameters":{}},
{"name":"launch/AddAutoToActorCommand","status":false,"description":"Add 'Auto' command on the top or bottom of Actor Command","parameters":{"commandName":"Auto Select","autoCommandPos":"0"}},
{"name":"launch/AdjustPictureGraphical","status":false,"description":"Plugin that adjust picture to graphical","parameters":{"GridSize":"48","TestMapId":"1"}},
{"name":"launch/ScreenZoom","status":false,"description":"[Ver1.1.0]Zoom screen whose center is specified character or player.","parameters":{}},
{"name":"launch/SVActorPositionMZ","status":false,"description":"[Ver1.1.3]Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"600","actor1 Ypos":"280","actor2 Xpos":"600 + 32","actor2 Ypos":"280 + 48","actor3 Xpos":"600 + 32 * 2","actor3 Ypos":"280 + 48 * 2","actor4 Xpos":"600 + 32 * 3","actor4 Ypos":"280 + 48 * 3"}},
{"name":"launch/MessageWindowPopup","status":true,"description":"Balloon Window Plugin","parameters":{"FontSize":"22","Padding":"10","AutoPopup":"true","FaceScale":"75","WindowLinkage":"true","BetweenLines":"4","FontSizeRange":"12","FontUpperLimit":"96","FontLowerLimit":"24","InnerScreen":"false","ShakeSpeed":"5","ShakeDuration":"60","NoUseTail":"false","MinWidthVariableId":"0","MinHeightVariableId":"0","lowerLimitX":"0","upperLimitX":"0","lowerLimitY":"0","upperLimitY":"0","tailImage":"","tailImageAdjustY":"0"}}
];
